language: shell
os: linux
dist: xential
services:
    - docker

before_install:
    - docker build -t michalpowaga/fibweb-tests -f ./fibweb/Dockerfile.dev ./fibweb

script:
    - docker run -e CI=true michalpowaga/fibweb-tests npm tests

after_success:
    - docker build -t michalpowaga/fibweb ./fibweb
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push michalpowaga/fibweb