language: shell
os: linux
dist: xenial
services:
    - docker

before_install:
    - docker build -t michalpowaga/fibweb-tests -f ./fibweb/Dockerfile.test ./fibweb

script:
    - docker run -e CI=true michalpowaga/fibweb-tests

after_success:
    - docker build -t michalpowaga/multidockerv2-fibweb ./fibweb
    - docker build -t michalpowaga/multidockerv2-proxy ./proxy
    - docker build -t michalpowaga/multidockerv2-fibapi ./fibapi
    - docker build -t michalpowaga/multidockerv2-fibservice ./fibservice

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push michalpowaga/multidockerv2-fibweb
    - docker push michalpowaga/multidockerv2-proxy
    - docker push michalpowaga/multidockerv2-fibapi
    - docker push michalpowaga/multidockerv2-fibservice

deploy:
    provider: elasticbeanstalk
    region: eu-west-1
    app: multidockerv2-1nd-try
    env: Multidockerv21ndTry-env
    bucket: elasticbeanstalk-eu-west-1-442152860333
    bucket_path: multidockerv2
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
        