version: "3"
services: 
    fibweb:
        build: 
            context: ./fibweb
            dockerfile: Dockerfile
        volumes: 
            - /app/node_modules
            - ./fibweb:/app
        stdin_open: true
        ports: 
            - 8080:80
